// GENERATED FILE - Replace this with the output of:
// flutterfire configure
//
// Run: dart pub global activate flutterfire_cli
//      flutterfire configure --project=<your-firebase-project-id>
//
// This file is a placeholder. You MUST replace it with the real
// firebase_options.dart generated by flutterfire before building.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
            'Unsupported platform: $defaultTargetPlatform');
    }
  }

  // REPLACE THESE VALUES with your actual Firebase project config

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwY04MUzHLYACQkeLeJQ9SWlWv7rziGcY',
    appId: '1:585114427159:android:e06d43c4d0cb7bbbb32152',
    messagingSenderId: '585114427159',
    projectId: 'freshbasket-c70e0',
    storageBucket: 'freshbasket-c70e0.firebasestorage.app',
  );

  // from: Firebase Console → Project Settings → Your Apps

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_U7i2eK9g0Rans2Us1i4Pkc53tcbltcA',
    appId: '1:585114427159:ios:6316415c05490cd8b32152',
    messagingSenderId: '585114427159',
    projectId: 'freshbasket-c70e0',
    storageBucket: 'freshbasket-c70e0.firebasestorage.app',
    iosBundleId: 'com.freshbasket.freshBasket',
  );

}