import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'core/routes/app_router.dart';
import 'core/services/notification_service.dart';
import 'core/theme/app_theme.dart';
import 'shared/providers/theme_provider.dart';

// Firebase options — generated by flutterfire configure
// Copy your actual google-services.json (Android) & GoogleService-Info.plist (iOS)
// into the project, then run: dart pub global run flutterfire_cli:flutterfire configure
// This placeholder will be replaced by the generated file.
import 'firebase_options.dart';

Future<void> main() async {
  await runZonedGuarded(_appMain, (error, stack) {
    debugPrint('[AppZone] Uncaught error: $error\n$stack');
    if (!kDebugMode) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    }
  });
}

Future<void> _appMain() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Load .env
  await dotenv.load(fileName: '.env');

  // Hive local storage
  await Hive.initFlutter();
  await Hive.openBox('settings');
  await Hive.openBox('cart');

  // Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Always catch Flutter framework errors (log in debug, report in release)
  FlutterError.onError = (details) {
    FlutterError.presentError(details);
    if (!kDebugMode) {
      FirebaseCrashlytics.instance.recordFlutterFatalError(details);
    }
  };

  if (!kDebugMode) {
    PlatformDispatcher.instance.onError = (error, stack) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
      return true;
    };
  }

  // Notifications
  await NotificationService.initialize();

  // Status bar style
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarBrightness: Brightness.light,
    statusBarIconBrightness: Brightness.dark,
  ));

  // Lock portrait
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  runApp(const ProviderScope(child: FreshBasketApp()));
}

class FreshBasketApp extends ConsumerWidget {
  const FreshBasketApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    final themeMode = ref.watch(themeProvider);

    // Hand the router reference to NotificationService so FCM taps can navigate.
    NotificationService.router = router;

    return MaterialApp.router(
      title: 'FreshBasket',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: themeMode,
      routerConfig: router,
      localizationsDelegates: const [
        DefaultMaterialLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
      ],
    );
  }
}
// runZonedGuarded: catches all uncaught dart errors, logs in debug / reports to Crashlytics in release
